# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69101eeac02128ef1fab35cc630ce287bb25a8ac8b2b836c6061d72ee0d4093f4f20f3b48b076668fbbfb4870e3c25830339586550dd365ad64953647c698ad0

test:
  secret_key_base: 6ed93ccbd4f87f1e8a51a17b228eb1aab365b8e1425af2458178a09c9fc883eedc2f853d8a3e5e0c64986073e8834dcf397ae54e58f90afb145048b293fdf0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
